### PR TITLE
Use the "default" directory to access J9's libjvm

### PR DESCRIPTION
**Pull request by babsingh**
Workaround for eclipse-openj9/openj9#14397.

Signed-off-by: Babneet Singh <sbabneet@ca.ibm.com>

### CODE REVIEW

**Comment by babsingh** [comment]
I was debating whether to just do minimal changes for `exeCallerAccessTest/CallerAccessTest` to pass on OSX or use `default/libjvm.*` with OpenJ9 everywhere. I chose the latter in order to avoid similar issues seen in https://github.com/eclipse-openj9/openj9/issues/14397 with other native tests.

Running personal build to verify these changes: https://github.com/eclipse-openj9/openj9/issues/14397.
Platforms: `x86-64_linux,x86-64_windows,ppc64_aix,x86-64_mac`
Test targets: `sanity.functional,sanity.openjdk`

Will remove this PR from the **draft state** if no failures are seen in the personal build. 

fyi @pshipton @tajila @keithc-ca

**Comment by pshipton** [comment]
The problem with using `default/libjvm` everywhere is that it might hide problems. Users do use, and are expected to use the redirector (from server or j9vm) and not the VM's libjvm directly. We used to have two or more VMs packaged (one for compressed, one non-compressed, one for realtime long ago). We haven't yet decided to do away with the redirector, so we expect it to work.

**Comment by keithc-ca** [comment]
I would hope that 'minimal' change is no change here. As Peter said, things should work with the redirector involved (as is the normal use case).

**Comment by pshipton** [comment]
True, the better approach is to spend time on figuring out what the problem with the redirector or test is, rather than on the workaround.

**Comment by babsingh** [comment]
Closing. Will exclude the failing test on OSX while the real fix is being developed.

**Pull request closed without merging**
